# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import NetworkCli_pb2 as NetworkCli__pb2


class NetworkCliStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SendQuery = channel.unary_unary(
        '/quickstep.NetworkCli/SendQuery',
        request_serializer=NetworkCli__pb2.QueryRequest.SerializeToString,
        response_deserializer=NetworkCli__pb2.QueryResponse.FromString,
        )


class NetworkCliServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SendQuery(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_NetworkCliServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SendQuery': grpc.unary_unary_rpc_method_handler(
          servicer.SendQuery,
          request_deserializer=NetworkCli__pb2.QueryRequest.FromString,
          response_serializer=NetworkCli__pb2.QueryResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'quickstep.NetworkCli', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
