# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: NetworkCli.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='NetworkCli.proto',
  package='quickstep',
  syntax='proto3',
  serialized_pb=_b('\n\x10NetworkCli.proto\x12\tquickstep\"\x1d\n\x0cQueryRequest\x12\r\n\x05query\x18\x01 \x01(\t\";\n\rQueryResponse\x12\x14\n\x0cquery_result\x18\x01 \x01(\t\x12\x14\n\x0c\x65rror_result\x18\x02 \x01(\t2N\n\nNetworkCli\x12@\n\tSendQuery\x12\x17.quickstep.QueryRequest\x1a\x18.quickstep.QueryResponse\"\x00\x62\x06proto3')
)




_QUERYREQUEST = _descriptor.Descriptor(
  name='QueryRequest',
  full_name='quickstep.QueryRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='query', full_name='quickstep.QueryRequest.query', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=60,
)


_QUERYRESPONSE = _descriptor.Descriptor(
  name='QueryResponse',
  full_name='quickstep.QueryResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='query_result', full_name='quickstep.QueryResponse.query_result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='error_result', full_name='quickstep.QueryResponse.error_result', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=121,
)

DESCRIPTOR.message_types_by_name['QueryRequest'] = _QUERYREQUEST
DESCRIPTOR.message_types_by_name['QueryResponse'] = _QUERYRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

QueryRequest = _reflection.GeneratedProtocolMessageType('QueryRequest', (_message.Message,), dict(
  DESCRIPTOR = _QUERYREQUEST,
  __module__ = 'NetworkCli_pb2'
  # @@protoc_insertion_point(class_scope:quickstep.QueryRequest)
  ))
_sym_db.RegisterMessage(QueryRequest)

QueryResponse = _reflection.GeneratedProtocolMessageType('QueryResponse', (_message.Message,), dict(
  DESCRIPTOR = _QUERYRESPONSE,
  __module__ = 'NetworkCli_pb2'
  # @@protoc_insertion_point(class_scope:quickstep.QueryResponse)
  ))
_sym_db.RegisterMessage(QueryResponse)



_NETWORKCLI = _descriptor.ServiceDescriptor(
  name='NetworkCli',
  full_name='quickstep.NetworkCli',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=123,
  serialized_end=201,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendQuery',
    full_name='quickstep.NetworkCli.SendQuery',
    index=0,
    containing_service=None,
    input_type=_QUERYREQUEST,
    output_type=_QUERYRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_NETWORKCLI)

DESCRIPTOR.services_by_name['NetworkCli'] = _NETWORKCLI

try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities


  class NetworkCliStub(object):
    # missing associated documentation comment in .proto file
    pass

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.SendQuery = channel.unary_unary(
          '/quickstep.NetworkCli/SendQuery',
          request_serializer=QueryRequest.SerializeToString,
          response_deserializer=QueryResponse.FromString,
          )


  class NetworkCliServicer(object):
    # missing associated documentation comment in .proto file
    pass

    def SendQuery(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_NetworkCliServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'SendQuery': grpc.unary_unary_rpc_method_handler(
            servicer.SendQuery,
            request_deserializer=QueryRequest.FromString,
            response_serializer=QueryResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'quickstep.NetworkCli', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaNetworkCliServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def SendQuery(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaNetworkCliStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def SendQuery(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()
    SendQuery.future = None


  def beta_create_NetworkCli_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('quickstep.NetworkCli', 'SendQuery'): QueryRequest.FromString,
    }
    response_serializers = {
      ('quickstep.NetworkCli', 'SendQuery'): QueryResponse.SerializeToString,
    }
    method_implementations = {
      ('quickstep.NetworkCli', 'SendQuery'): face_utilities.unary_unary_inline(servicer.SendQuery),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_NetworkCli_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('quickstep.NetworkCli', 'SendQuery'): QueryRequest.SerializeToString,
    }
    response_deserializers = {
      ('quickstep.NetworkCli', 'SendQuery'): QueryResponse.FromString,
    }
    cardinalities = {
      'SendQuery': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'quickstep.NetworkCli', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
